#dockerfile
FROM ubuntu:20.04

WORKDIR /app

RUN apt-get update && apt-get install -y && \
    apt-get install -y python3 python3-pip && \
    apt-get  install iproute2 -y

COPY ip_check.py /app/

CMD ["python3", "ip_check.py"]
